### ISSUE TITLE
update cli to work with core's tip

### ISSUE THREAD

**Issue by tremblap** [flucoma/flucoma-cli#13]
At the moment, compiling is broken if we use the tip of flucoma-core but works with the commit pegged in the cmake. I was requested to make an issue with this :)

**Comment by weefuzzy** [comment]
This may be as simple as updating the CLIBufferAdaptor, I don't know. 

We pegged this for a reason, which was to avoid it being any more of a time-sink whilst we sorted out functionality for TB2 stuff on Max and SC, which is still in flux AFAIC.  If there's a clear benefit to putting time into this, I'll prioritise accordingly.

**Comment by tremblap** [comment]
ok I'll manually put core at that commit and check it for you with love

**Comment by jamesb93** [comment]
Is this still horrid to fix @weefuzzy ? I'd like to use the CLI again for some personal stuff and could write the small bit of code to deal with fluid.bufstft~ but I can't solve the build problem on my own due to my lack of C++ knowledge.

**Comment by weefuzzy** [comment]
It's got no less horrid 😆 I've not investigated at all what would be needed, beyond updating the BufferAdaptor. If it's just that, then simples. If it's not just that, then 🤷 (and getting the DataSet objects to work with CLI is a whole other jug of ferrets)

**Comment by jamesb93** [comment]
> (and getting the DataSet objects to work with CLI is a whole other jug of ferrets)

A jug of ferrets indeed. I can't imagine one working with datasets as a cli interface but I can definitely imagine someone wanting to do JSON > `fluid-umap` > JSON. In a sense, datasets~ would be invisible beasties under the hood but the processors are exposed as cli things.
