### ISSUE TITLE
Add Arch/Manjaro install instructions (flucoma-cli is now on the AUR)

### ISSUE THREAD

**Issue by madskjeldgaard** [flucoma/flucoma-cli#3]
hi!
First off: Great work with these tools. They are simply amazing. 
I just wanted to say that flucoma-cli is now on the AUR / Arch User Repository and can now be compiled and downloaded by executing:
`yay -S flucoma-cli-git` 
on Arch Linux and Manjaro. 
Best

**Comment by madskjeldgaard** [comment]
link here: https://aur.archlinux.org/packages/flucoma-cli-git/

**Comment by madskjeldgaard** [comment]
There's also a package which pulls the latest pre built version from here https://aur.archlinux.org/packages/flucoma-cli/

**Comment by weefuzzy** [comment]
@madskjeldgaard that's amazing, thanks so much. I'll update the README with this.
